config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  mount Thredded::Engine => '/forum'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  resources :users do
    get :friends, on: :member
    post :request_friendship, on: :collection
    post :cancel_friend_request, on: :collection
    post :accept_friendship, on: :collection
    post :decline_friendship, on: :collection
    post :unfriend, on: :collection
  end
  resources :readers_group_members
  resources :readers_groups
  resources :roles
  resources :book_ratings
  resources :ratings
  resources :genres
  resources :books
  resources :favourite_genres
  resources :reading_histories do
    post :mark_as_read, on: :collection
    post :mark_as_unread, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/active_admin_adapter.rb
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin == true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable 'name'

  belongs_to :genre
  has_many :reading_histories

  def read_by?(user)
    reading_histories.where(user_id: user.id, status: 'read').exists?
  end

  def mark_as_read!(user)
    reading_histories.create(user_id: user.id, status: 'read')
  end

  def mark_as_unread!(user)
    reading_histories.find_by(user_id: user.id, status: 'read').destroy
  end
end

app/models/favourite_genre.rb
class FavouriteGenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre

  validates :genre_id, uniqueness: { scope: :user_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/readers_group.rb
class ReadersGroup < ApplicationRecord
end

app/models/reading_history.rb
class ReadingHistory < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_friendship

  ratyrate_rater

  has_many :favourite_genres

  validates :username, uniqueness: true, format: { with: /\A\w*\z/, message: "only allows letters" }

  def friend_request_received?(friend)
    HasFriendship::Friendship.find_relation(self, friend, status: 1).any?
  end

  def friend_request_sent?(friend)
    HasFriendship::Friendship.find_relation(self, friend, status: 0).any?
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split(' ').first
      user.last_name = auth.info.name.split(' ').last
      user.image = auth.info.image
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    puts request.env['omniauth.auth'].inspect
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @users = @users.where("first_name LIKE :name OR last_name LIKE :name OR username LIKE :name", name: "%#{params[:search_term]}%")
  end

  def friends
    @requested_friends = current_user.requested_friends
    @pending_friends = current_user.pending_friends
    @friends = current_user.friends
  end

  def request_friendship
    user = User.find(params[:user_id])
    if current_user.friend_request(user)
      flash[:success] = 'Friend request sent successfully.'
    else
      flash[:error] = 'Failed to send friend request. Please try again.'
    end
    render :response, locals: { user: user }
  end

  def cancel_friend_request
    user = User.find(params[:user_id])
    if current_user.remove_friend(user)
      flash[:success] = 'Friend request cancelled successfully.'
    else
      flash[:error] = 'Failed to cancel friend request. Please try again.'
    end
    render :response, locals: { user: user }
  end

  def accept_friendship
    user = User.find(params[:user_id])
    if current_user.accept_request(user)
      flash[:success] = 'Friend request accepted successfully.'
    else
      flash[:error] = 'Failed to accept friend request. Please try again.'
    end
    render :response, locals: { user: user }
  end

  def decline_friendship
    user = User.find(params[:user_id])
    if current_user.decline_request(user)
      flash[:success] = 'Friend request declined successfully.'
    else
      flash[:error] = 'Failed to decline friend request. Please try again.'
    end
    render :response, locals: { user: user }
  end

  def unfriend
    user = User.find(params[:user_id])
    if current_user.remove_friend(user)
      flash[:success] = 'Friend removed successfully.'
    else
      flash[:error] = 'Failed to remove friend request. Please try again.'
    end
    render :response, locals: { user: user }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym]
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(
        content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
          concat content_tag(:button, '×'.html_safe, class: "close", data: { dismiss: 'alert' })
          concat message
        end
      )
    end
    nil
  end
end

app/helpers/book_ratings_helper.rb
module BookRatingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/users/_user_card.html.haml
.card.bg-light.mb-3{ id: "user_#{user.id}", style: 'max-width: 20rem;' }
  .card-header
    = image_tag 'cropped-favicon.png', :alt => "Card image cap", class: 'card-img-top'
    %h4.card-title
      = "#{user.first_name} #{user.last_name}"
    %h5.card-subtitle.text-muted
      %em= user.username
  .card-body.text-secondary
    %p.card-text
      = "Books Read: 5" # TODO: Read books count to be dynamic
    %p.card-text
      = "Books in Wishlist: 5" # TODO: Books in Wishlist count to be dynamic
  - if current_user != user
    .card-footer
      %small.text-muted
        - if current_user.friends_with?(user)
          = form_with url: unfriend_users_path, method: :post, remote: true do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit '- Unfriend', class: 'btn btn-danger'
        - elsif current_user.friend_request_received?(user)
          = form_with url: accept_friendship_users_path, method: :post, remote: true do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit '✔ Accept', class: 'btn btn-success'
          = form_with url: decline_friendship_users_path, method: :post, remote: true do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit '× Decline', class: 'btn btn-danger'
        - elsif current_user.friend_request_sent?(user)
          = form_with url: cancel_friend_request_users_path, method: :post, remote: true do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit 'Cancel Request', class: 'btn btn-warning'
        - else
          = form_with url: request_friendship_users_path, method: :post, remote: true do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit '+ Add as friend', class: 'btn btn-primary'

app/views/users/_user_cards.html.haml
- users.in_groups_of(3, false).each do |group_users|
  .card-deck
    - group_users.each do |user|
      = render 'user_card', user: user
      %br
  %br

app/views/users/friends.html.haml
- content_for :title, ' | Friends'

%hr
%h3
  Received Friend Requests
  %span.badge.badge-pill.badge-secondary= @requested_friends.count
%hr
- if @requested_friends.present?
  = render 'user_cards', users: @requested_friends
- else
  = 'All of your friend requests have been responded!'
%hr
%h3
  Sent Friend Requests
  %span.badge.badge-pill.badge-secondary= @pending_friends.count
%hr
- if @pending_friends.present?
  = render 'user_cards', users: @pending_friends
- else
  = 'There are no pending requests. You have responded to all friend requests received!'
%hr
%h3
  Friends
  %span.badge.badge-pill.badge-secondary= @friends.count
%hr
- if @friends.present?
  = render 'user_cards', users: @friends
- else
  = 'You have no friends yet!'

app/views/users/index.html.haml
- content_for :title, ' | Readers'

- if @users.present?
  = render 'user_cards', users: @users
- else
  = "There are no users found with search term '#{params[:search_term]}'"

app/views/users/response.js.erb
$('#user_' + '<%= user.id %>').replaceWith("<%=j render 'user_card', user: user %>");
var cardHeader = $('#user_' + '<%= user.id %>' + ' .card-header');
cardHeader.before('<%=j flash_messages %>');
cardHeader.siblings('.alert').fadeOut(5000);