config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  mount Thredded::Engine => '/forum'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  resources :users do
    get :friends, on: :member
    post :request_friendship, on: :collection
    post :cancel_friend_request, on: :collection
    post :accept_friendship, on: :collection
    post :decline_friendship, on: :collection
    post :unfriend, on: :collection
  end
  resources :readers_group_members
  resources :readers_groups
  resources :roles
  resources :book_ratings
  resources :ratings
  resources :genres
  resources :books
  resources :favourite_genres
  resources :reading_histories do
    post :mark_as_read, on: :collection
    post :mark_as_unread, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/active_admin_adapter.rb
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin == true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable 'name'

  belongs_to :genre
  has_many :reading_histories

  def read_by?(user)
    reading_histories.where(user_id: user.id, status: 'read').exists?
  end

  def mark_as_read!(user)
    reading_histories.create(user_id: user.id, status: 'read')
  end

  def mark_as_unread!(user)
    reading_histories.find_by(user_id: user.id, status: 'read').destroy
  end
end

app/models/favourite_genre.rb
class FavouriteGenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre

  validates :genre_id, uniqueness: { scope: :user_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/readers_group.rb
class ReadersGroup < ApplicationRecord
end

app/models/reading_history.rb
class ReadingHistory < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_friendship

  ratyrate_rater

  has_many :favourite_genres

  validates :username, uniqueness: true, format: { with: /\A\w*\z/, message: "only allows letters" }

  def friend_request_received?(friend)
    HasFriendship::Friendship.find_relation(self, friend, status: 1).any?
  end

  def friend_request_sent?(friend)
    HasFriendship::Friendship.find_relation(self, friend, status: 0).any?
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split(' ').first
      user.last_name = auth.info.name.split(' ').last
      user.image = auth.info.image
    end
  end
end

app/controllers/book_ratings_controller.rb
class BookRatingsController < InheritedResources::Base
  layout 'layouts/admin'
  private

    def book_rating_params
      params.require(:book_rating).permit(:rating_comment, :book_id, :user_id, :rating_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym]
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(
        content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
          concat content_tag(:button, '×'.html_safe, class: "close", data: { dismiss: 'alert' })
          concat message
        end
      )
    end
    nil
  end
end

app/helpers/book_ratings_helper.rb
module BookRatingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/book_ratings/_form.html.haml
= form_with(model: book_rating, local: true) do |form|
  - if book_rating.errors.any?
    #error_explanation
      %h2
        = pluralize(book_rating.errors.count, "error")
        prohibited this book_rating from being saved:
      %ul
        - book_rating.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :rating_comment
    = form.text_field :rating_comment, id: :book_rating_rating_comment
  .field
    = form.label :book_id
    = form.text_field :book_id, id: :book_rating_book_id
  .field
    = form.label :user_id
    = form.text_field :user_id, id: :book_rating_user_id
  .field
    = form.label :rating_id
    = form.text_field :rating_id, id: :book_rating_rating_id
  .actions
    = form.submit

app/views/book_ratings/edit.html.haml
%h1 Editing Book Rating
= render 'form', book_rating: @book_rating
= link_to 'Show', @book_rating
|
= link_to 'Back', book_ratings_path

app/views/book_ratings/index.html.haml
%h1 Book Ratings
%table
  %thead
    %tr
      %th Rating comment
      %th Book
      %th User
      %th Rating
      %th{:colspan => "3"}
  %tbody
    - @book_ratings.each do |book_rating|
      %tr
        %td= book_rating.rating_comment
        %td= book_rating.book
        %td= book_rating.user
        %td= book_rating.rating
        %td= link_to 'Show', book_rating
        %td= link_to 'Edit', edit_book_rating_path(book_rating)
        %td= link_to 'Destroy', book_rating, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Book Rating', new_book_rating_path

app/views/book_ratings/new.html.haml
%h1 New Book Rating
= render 'form', book_rating: @book_rating
= link_to 'Back', book_ratings_path

app/views/book_ratings/show.html.haml
%p
  %strong Rating comment:
  = @book_rating.rating_comment
%p
  %strong Book:
  = @book_rating.book
%p
  %strong User:
  = @book_rating.user
%p
  %strong Rating:
  = @book_rating.rating
= link_to 'Edit', edit_book_rating_path(@book_rating)
|
= link_to 'Back', book_ratings_path